version: 2.0

jobs:
  build:
    docker:
    - image: circleci/ruby:2.6.7-node-browsers
      environment:
        BUNDLER_VERSION: 2.1.2
        RAILS_ENV: test
    - image: circleci/mysql:5.7 ## dbの指定
      environment:
        MYSQL_ROOT_HOST: '127.0.0.1'
        MYSQL_PASSWORD: 'password'
    working_directory: ~/repo

    steps:
      - checkout # git codeをプルダウン
      - run:
          name: bundle install
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  test:
    docker:
    - image: circleci/ruby:2.6.7-node-browsers
      environment:
        RAILS_ENV: test
    - image: circleci/mysql:5.7 ## dbの指定
      environment:
        MYSQL_ROOT_HOST: 127.0.0.1
        MYSQL_PASSWORD: password
    steps:
      - checkout
      - run: bundle install --path vendor/cache
      - run:
          name: setup db
          command: bundle exec rake db:create && bundle exec rails db:migrate
      - run:
          name: runs test
          command: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build

